Refactorization and .git dir checking.

diff --git a/bin/git-sizes b/bin/git-sizes
--- a/bin/git-sizes
+++ b/bin/git-sizes
@@ -3,10 +3,22 @@
 PROJECT_DIR=.
 GIT_DIR=.git
 
-if [ ! -d $GIT_DIR ]; then
-	echo "ERROR: Not in a Git repository."
-	exit 1
-fi
+function find_git_base_dir() {
+	PROJECT_DIR=$(pwd)
+	while [ ! -d $PROJECT_DIR/$GIT_DIR -a $PROJECT_DIR != '/' ]; do
+		PROJECT_DIR=$(dirname $PROJECT_DIR)
+	done
+}
+
+function check_git_dir() {
+	if [ ! -d $GIT_DIR ]; then
+		find_git_base_dir
+		if [ "$PROJECT_DIR" == "/" ]; then
+			echo "ERROR: Not in a Git repository: $(pwd)"
+			exit 1
+		fi
+	fi
+}
 
 function sizes() {
 	if [ "$2" != "" ]; then
@@ -20,12 +32,14 @@ function sizes() {
 	repo_bsize=$(echo $bsize | cut -d' ' -f1)
 }
 
-sizes $PROJECT_DIR
-echo "Git repository size : $repo_size ($repo_bsize B)"
+check_git_dir
 
-sizes $GIT_DIR
-echo "Git directory size  : $repo_size ($repo_bsize B)"
+sizes $PROJECT_DIR
+echo "Total size   : $repo_size ($repo_bsize B)"
+
+sizes $PROJECT_DIR/$GIT_DIR
+echo "Git dir size : $repo_size ($repo_bsize B)"
 
 sizes $PROJECT_DIR $GIT_DIR
-echo "Source code size    : $repo_size ($repo_bsize B)"
+echo "Project size : $repo_size ($repo_bsize B)"
 
