Functions to other git scripts.

diff --git a/bin/git-tools b/bin/git-tools
--- a/bin/git-tools
+++ b/bin/git-tools
@@ -7,3 +7,28 @@ if [ "$(basename $0)" == "$FILE_NAME" ]; then
 	exit 1
 fi
 
+# Default project directory. This variable will be updated with the
+# call to 'find_git_base_dir'.
+PROJECT_DIR=.
+
+# Default git repo directory.
+GIT_DIR=.git
+
+# Search for Git repo base dir.
+function find_git_base_dir() {
+	PROJECT_DIR=$(pwd)
+	while [ ! -d $PROJECT_DIR/$GIT_DIR -a $PROJECT_DIR != '/' ]; do
+		PROJECT_DIR=$(dirname $PROJECT_DIR)
+	done
+}
+
+# Checks if we are in a Git repo.
+function check_git_dir() {
+	if [ ! -d $GIT_DIR ]; then
+		find_git_base_dir
+		if [ "$PROJECT_DIR" == "/" ]; then
+			echo "ERROR: Not in a Git repository: $(pwd)"
+			exit 1
+		fi
+	fi
+}
