Add option parsing.

diff --git a/bin/one-line-log b/bin/one-line-log
--- a/bin/one-line-log
+++ b/bin/one-line-log
@@ -1,5 +1,48 @@
 #!/bin/bash
 
+SKIP_AFTER=0
+SKIP_BEFORE=0
+REGEX=""
+
+function usage() {
+	echo "$(basename $0) - Utility to show a multiline log as a one single line (overriding previous)."
+	echo "Diego Lago González <diego.lago.gonzalez@gmail.com>"
+	echo "Usage: <command> | one-line-log [options]"
+	echo "Options:"
+	echo "  -A <n>     : Skip <n> lines after."
+	echo "  -B <n>     : Skip <n> lines before."
+	echo "  -r <regex> : Skip lines matching <regex> regular expression."
+	echo "  -h         : Show this help."
+	exit 1
+}
+
+function parse_options() {
+	while getopts ":A:B:r:h" opt; do
+		case "$opt" in
+			A)
+				SKIP_AFTER=$OPTARG
+			;;
+			B)
+				SKIP_BEFORE=$OPTARG
+			;;
+			r)
+				REGEX=$OPTARG
+			;;
+			h)
+				usage
+			;;
+			\?)
+				echo "ERROR: Invalid option: -$OPTARG" 1>&2
+				exit 1
+			;;
+			:)
+				echo "ERROR: Option -$OPTARG requires an argument." 1>&2
+				exit 1
+			;;
+		esac
+	done
+}
+
 function one_line_log() {
 	while read; do
 		echo -e "\r\033[0K${REPLY}" | tr -d '\n'
@@ -8,6 +51,7 @@ function one_line_log() {
 }
 
 function main() {
+	parse_options $@
 	one_line_log
 }
 
