Add 'upgrade' command to do an 'aptitude safe-upgrade'.

diff --git a/bin/ubuntu b/bin/ubuntu
--- a/bin/ubuntu
+++ b/bin/ubuntu
@@ -37,7 +37,13 @@ function usage() {
 	echo "Usage: $(basename $0) [command] [options]"
 	echo "Commands:"
 	echo "  snapshot : Makes an btrfs snapshot of the btrfs Ubuntu layout."
+	echo "   upgrade : Upgrades all the systema packages."
 	echo "      help : Show this help and exits."
+}
+
+function upgrade_system() {
+	type aptitude > /dev/null 2>&1 || error "Unable to do a full upgrade. 'aptitude' command not found." -5
+	sudo aptitude safe-upgrade -y
 }
 
 function check_filesystem_type() {
@@ -82,6 +88,9 @@ function main() {
 	case "$command" in
 		"snapshot")
 			make_snapshot $@
+		;;
+		"upgrade")
+			upgrade_system $@
 		;;
 		"help")
 			credits
