Error messages and log function.

diff --git a/bin/ubuntu b/bin/ubuntu
--- a/bin/ubuntu
+++ b/bin/ubuntu
@@ -2,6 +2,14 @@
 
 VERSION="0.1"
 
+VERBOSE=no
+
+function log() {
+	if [ "$VERBOSE" == "yes" ]; then
+		echo $@
+	fi
+}
+
 function error() {
 	echo "ERROR: $1" 1>&2
 	if [ -n "$2" -a $2 != 0 ]; then
@@ -52,14 +60,16 @@ function make_snapshot() {
 	dev_fs=$(/bin/df -T | grep \/$ | awk '{print $2}')
 	check_filesystem_type $dev_fs
 	tmp_dir=$(mktemp -d /tmp/btrfs-snapshot-XXXXXXXX)
-	mount -t $dev_fs $root_dev $tmp_dir
+	mount -t $dev_fs $root_dev $tmp_dir || error "Cannot mount $dev_fs" -4
 	# Device is mounted. Do the actual snapshot.
 	local date=$(date +%Y%m%d%H%M%S)
 	for dir in $tmp_dir/*; do
 		to_snapshot=$(echo $(basename $dir) | grep "^@" | grep -v snapshot)
 		if [ -n "$to_snapshot" ]; then
-			echo "Do snapshot from $to_snapshot to $to_snapshot-$date"
 			echo "btrfs subvolume snapshot $tmp_dir/$to_snapshot $tmp_dir/$to_snapshot-$date"
+			if [ $? != 0 ]; then
+				error "Cannot create snapshot from $tmp_dir/$to_snapshot to $tmp_dir/$to_snapshot-$date" -5
+			fi
 		fi
 	done
 	umount $tmp_dir
